name: Version Update

on:
  push:
    branches:
      - master  # Specify the master branch
      
jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # Adjust based on your project

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Update version
      run: gitversion /output json

    - name: Set up Git credentials
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit version update
      run: |
        git checkout master  # Ensure you're on the master branch
        git add .
        git commit -m "Update version to $(gitversion /output json | jq -r '.FullSemVer')"

    - name: Push changes
      run: git push origin master  # Explicitly push to the master branch
